plugins {
    id 'com.android.application'
}

android {
    namespace 'company.taowind.aethercenter'
    compileSdk 35

    defaultConfig {
        applicationId 'company.taowind.aethercenter'
        minSdk 28
        targetSdk 31
        versionCode 2
        versionName '0.1.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
